name: Publish Development Backend Docker image

on:
  push:
    tags:
      - '*-dev'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-build-push
        name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/tl-php-fpm:${{ steps.docker-tag.outputs.tag }}
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/tl-php-fpm:development
